{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-config
  labels:
    app: {{ template "fluent-bit.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
{{- if .Values.parsers.enabled }}
        Parsers_File parsers_custom.conf
{{- end }}
{{- if .Values.metrics.enabled }}
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
{{- end }}

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              {{ .Values.filter.kubeTag }}.*
        Refresh_Interval 5
        Mem_Buf_Limit    {{ .Values.input.tail.memBufLimit }}
        Skip_Long_Lines  On
{{- if .Values.trackOffsets }}
        DB               /tail-db/tail-containers-state.db
        DB.Sync          Normal
{{- end }}
{{ .Values.extraInputs | indent 8 }}

    [FILTER]
        Name                kubernetes
        Match               {{ .Values.filter.kubeTag }}.*
        Kube_URL            {{ .Values.filter.kubeURL }}
        Kube_CA_File        {{ .Values.filter.kubeCAFile }}
        Kube_Token_File     {{ .Values.filter.kubeTokenFile }}
{{- if .Values.filter.mergeJSONLog }}
        Merge_Log           On
{{- end }}
{{- if .Values.filter.enableParser }}
        K8S-Logging.Parser  On
{{- end }}
{{- if .Values.filter.enableExclude }}
        K8S-Logging.Exclude On
{{- end }}
{{ .Values.extraFilters | indent 8 }}

{{ if eq .Values.backend.type "file" }}
    [OUTPUT]
        Name  file
        Match *
        Path {{ .Values.backend.file.path  }}

{{ else if eq .Values.backend.type "syslog" }}
    [OUTPUT]
        Name syslog
        Match *
        ClusterSinks [{"addr":"{{.Values.backend.syslog.host }}:{{ .Values.backend.syslog.port }}"}]
{{- if .Values.backend.syslog.namespace }}
        Sinks [{"addr":"{{.Values.backend.syslog.host }}:{{ .Values.backend.syslog.port }}", "namespace": "{{ .Values.backend.syslog.namespace}}"}]
{{- end }}
{{- end }}
{{ .Values.extraOutputs | indent 8 }}

  parsers.conf: |-
{{- if .Values.parsers.regex }}
{{- range .Values.parsers.regex }}
    [PARSER]
        Name        {{ .name }}
        Format      regex
        Regex       {{ .regex }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.json }}
{{- range .Values.parsers.json }}
    [PARSER]
        Name        {{ .name }}
        Format      json
{{- if .timeKeep }}
        Time_Keep    {{ .timeKeep }}
{{- end }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .decodeFieldAs  }}
        Decode_Field_As {{ .decodeFieldAs }} {{ .decodeField | default "log" }}
{{- end }}
{{ end }}
{{- end }}

{{- end -}}
